# This workflow will upload a Python Package
# using Twine when a release is created

name: publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # tags are of the form `v0.8.0`, PEP-440 versions are of the form `0.8.0`
    - name: Update version in pyproject.toml to ${{ github.ref_name }}
      run: |
        VERSION="${GITHUB_REF_NAME#v}"
        sed -i "s/^version = \"0.0.0.dev0\"$/version = \"${VERSION}\"/" pyproject.toml
        grep -q "^version = \"${VERSION}\"$" pyproject.toml

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build twine

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python3 -m build
        python3 -m twine upload dist/*
