name: tests

on: [pull_request]

jobs:
  test:
    uses: nmichlo/.github/.github/workflows/pytest.yaml@main
    with:
      python-versions: '["3.12", "3.13", "3.14"]'
      install-extras: "test"
      pytest-args: "--color=yes --verbose"
